services:
  php:
    image: tugboatqa/php:8.1-apache
    default: true
    depends: mysql
    commands:
      init:
        - apt-get update

        - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
        - apt-get install -y rsync libzip-dev nodejs libmagickwand-dev

        - a2enmod rewrite headers

        - docker-php-ext-install mysqli exif zip opcache
        - pecl install imagick-beta -y
        - docker-php-ext-enable imagick

        - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        - chmod +x wp-cli.phar
        - mv wp-cli.phar /usr/local/bin/wp

        - mkdir -p "${TUGBOAT_ROOT}/build"
        - ln -snf "${TUGBOAT_ROOT}/build" "${DOCROOT}"

      update:
        # Copy the uploads directory from an external server. The public
        # SSH key found in the Tugboat Repository configuration must be
        # copied to the external server in order to use rsync over SSH.
#        - mkdir -p "${DOCROOT}/wp-content/uploads" || /bin/true
#        - rsync -av --delete user@example.com:/path/to/wp-content/uploads/ "${DOCROOT}/wp-content/uploads/"
#        - chgrp -R www-data "${DOCROOT}/wp-content/uploads"
#        - find "${DOCROOT}/wp-content/uploads" -type d -exec chmod 2775 {} \;
#        - find "${DOCROOT}/wp-content/uploads" -type f -exec chmod 0664 {} \;
        - npm install
        - npm run build
        - wp --allow-root --path=$DOCROOT config create
            --dbhost=mysql
            --dbname=tugboat
            --dbuser=tugboat
            --dbpass=tugboat
        - wp --allow-root --path=$DOCROOT core install
            --url=example.com
            --title="WordPress Core"
            --admin_user=admin
            --admin_password=admin
            --admin_email=admin@example.com
        - wp --allow-root --path=$DOCROOT plugin install wordpress-importer --activate
        - curl -O https://raw.githubusercontent.com/WPTT/theme-test-data/master/theme-preview.xml
        - wp --allow-root --path=$DOCROOT --authors=create import theme-preview.xml
        - apt-get clean
        - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

      build:
        - npm install
        - npm run build
        - |
          if [ "x${TUGBOAT_BASE_PREVIEW}" != "x" ]; then
              wp --allow-root --path="${DOCROOT}" search-replace "${TUGBOAT_BASE_PREVIEW_URL_HOST}" "${TUGBOAT_SERVICE_URL_HOST}" --skip-columns=guid
          else
              wp --allow-root --path="${DOCROOT}" search-replace 'example.com' "${TUGBOAT_SERVICE_URL_HOST}" --skip-columns=guid
          fi

  mysql:
    image: tugboatqa/mysql:5

